### PR TITLE
Updated cluster yaml to latest image tag

### PR DESCRIPTION
**Pull request by amiramm**
The latest image tag is 5.4.0-19.

### CODE REVIEW

**Comment by michalrabinowitch** [comment]
@danni-m should this get a QA approval ? [current operator + new RS ]

**Comment by michalrabinowitch** [comment]
@amiramm @danni-m maybe we should hold this until the coming release?

**Comment by amiramm** [comment]
> @danni-m should this get a QA approval ? [current operator + new RS ]

I'll check with QA

**Comment by amiramm** [comment]
> > @danni-m should this get a QA approval ? [current operator + new RS ]
> 
> I'll check with QA

@danni-m -17 was tested and released with this operator.

**Pull request closed without merging**
